#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
# import sys

# append project directory to path so predict.py can be imported
# sys.path.append('.')
# from predict import MODEL_CACHE
MODEL_CACHE = "checkpoints"

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# Download GFPGANv1.4
os.system("cd checkpoints && wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth")

# Download inswapper_128.onnx
os.system("cd checkpoints && wget https://huggingface.co/ashleykleynhans/inswapper/resolve/main/inswapper_128.onnx")
# backup download link https://huggingface.co/CountFloyd/deepfake/resolve/main/inswapper_128.onnx